spring.application.name=csv-google-form-app
server.port=8030

#| Environment | Setting                         |
#| ----------- | ------------------------------- |
#| Local Dev   | `google.form.mock.enabled=true` |
#| QA          | `true`                          |
#| Production  | `false`                         |
google.form.mock.enabled=false
google.form.rate.limit.per.second=3
